[package]
name = "pj"
version = "0.1.0"
authors = ["RoccoDev <roccodev.business@gmail.com>"]
description = "Reserved for later use."
license = "GPL-3.0-or-later"

[dependencies]
serde_json = "1.0"
termion = "1.5.1"